import { Request, Response } from 'express';
import tesseract from 'tesseract.js';
import { prisma } from '../utils/db';

export const uploadPrescription = async (req: Request, res: Response) => {
  try {
    if (!req.file) {
      return res.status(400).json({ message: 'No file uploaded' });
    }

    const patientId = req.body.patientId || 'dummy-patient-123'; // Hardcoded for demo

    // 1. Process image with Tesseract OCR
    const { data: { text } } = await tesseract.recognize(req.file.buffer, 'eng');

    // 2. Save medical record with extracted text
    const record = await prisma.medicalRecord.create({
      data: {
        patientId,
        documentUrl: 'local/buffer', // Ideally S3 bucket URL
        extractedText: text,
        notes: 'Autogenerated from OCR upload'
      }
    });

    res.status(201).json({
      message: 'Processing complete',
      record
    });
  } catch (error: any) {
    console.error("OCR Error:", error);
    res.status(500).json({ error: error.message });
  }
};
